	
--III
	CREATE DATABASE RiverPlate
	GO
	USE RiverPlate
	GO
	CREATE TABLE STUDENT
	(
		studentNo INT IDENTITY PRIMARY KEY
		,studentName VARCHAR(50)
		,studentAddress VARCHAR(100)
		,phoneNo INT
	)
	GO
	CREATE TABLE DEPARTMENT
	(
		deptNo INT IDENTITY PRIMARY KEY
		,deptName VARCHAR(50)
		,managerName CHAR(30)
	)
	GO
	CREATE TABLE ASSIGINMENT
	(
		assignmentNo INT IDENTITY PRIMARY KEY
		,description VARCHAR(100)
	)
	GO
	CREATE TABLE WORKS_ASSIGN
	(
		jobId INT IDENTITY PRIMARY KEY
		,studentNo INT REFERENCES STUDENT(studentNo)
		,assignmentNo INT REFERENCES ASSIGNMENT(assignmentNo)
		,totalHours INT
		,jobDetails XML
	)
	GO
	CREATE CLUSTERED INDEX IX_Student ON STUDENT(studentNo)
	GO
	ALTER INDEX IX_Student 
	ON STUDENT
	DISABLE; 
	GO
	CREATE  NON-CLUSTERED  INDEX IX_Dept ON DEPARTMENT(deptNo, deptName, managerName)
	GO

